package com.patent;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import com.patent.model.Inventor;
import com.patent.model.TestModel;

public class TestOracle {

	static final String JDBC_URL = "jdbc:oracle:thin:@localhost:1521:orcl";
	static final String USER = "sys as sysdba";
	static final String PASSWORD = "sys123";

	public static void main(String[] args) {

		TestModel tm = new TestModel();
		Inventor inventor = new Inventor();
		inventor.setAddress("27");
		inventor.setApplicationNumber("85858");
		inventor.setName("aiamsi");
		inventor.setCountry("bharat");
		inventor.setNationality("bhartiye");

		tm.setApplicationNumber("95959");
		tm.setTestName("SUMMARY OF THE INVENTION\r\n"
				+ "5\r\n"
				+ "[0004] It is desirable that the generation of a loss attributable to the learning can\r\n"
				+ "be inhibited during the learning of the clutch. In learning based on a change in rotation,\r\n"
				+ "for example, a loss attributable to co-rotation and a change in rotation speed may be\r\n"
				+ "generated.\r\n"
				+ "10 [0005] An object of the invention is to provide a vehicle control device that is\r\n"
				+ "capable of inhibiting the generation of a loss attributable to the learning of an engagement\r\n"
				+ "position of a clutch.\r\n"
				+ "[0006] A vehicle control device according to the invention includes a rotating\r\n"
				+ "machine, a clutch transmitting torque to the rotating machine when engaged, and a\r\n"
				+ "15 detection unit detecting a change in cogging torque of the rotating machine, and learns an\r\n"
				+ "engagement position of the clutch based on a change in the cogging torque during a\r\n"
				+ "change in a clutch stroke of the clutch in a case where the rotating machine is stationary.\r\n"
				+ "[0007] It is preferable that the vehicle control device described above further\r\n"
				+ "includes a rotation angle position detecting device detecting a rotation angle position of\r\n"
				+ "20 the rotating machine and the detection unit detects the change in the cogging torque based\r\n"
				+ "on a detection result of the rotation angle position detecting device.\r\n"
				+ "[0008] In the vehicle control device described above, it is preferable that the\r\n"
				+ "clutch stroke at which the rotation angle position begins to change during an increase in\r\n"
				+ "the clutch stroke is learned as the engagement position of the clutch.\r\n"
				+ "25 [0009] In the vehicle control device described above, it is preferable that the\r\n"
				+ "clutch stroke at which the rotation angle position begins to remain unchanged during a\r\n"
				+ "decrease in the clutch stroke is learned as the engagement position of the clutch.\r\n"
				+ "[0010] In the vehicle control device described above, it is preferable that an\r\n"
				+ "3\r\n"
				+ "average stroke of the clutch stroke at which the rotation angle position begins to change\r\n"
				+ "during an increase in the clutch stroke and the clutch stroke at which the rotation angle\r\n"
				+ "position begins to remain unchanged during a decrease in the clutch stroke is learned as\r\n"
				+ "the engagement position of the clutch.\r\n"
				+ "[0011] It is preferable that the vehicle control device described above includ5 es\r\n"
				+ "an engine, a first rotating machine, a second rotating machine, and a differential\r\n"
				+ "mechanism in which the engine, the first rotating machine, and the second rotating\r\n"
				+ "machine are connected to different rotating elements, the clutch transmits torque to the\r\n"
				+ "first rotating machine when engaged, the detection unit detects a change in cogging\r\n"
				+ "10 torque of the first rotating machine, an engagement position of the clutch is learned based\r\n"
				+ "on a change in the cogging torque during a change in a clutch stroke of the clutch in a\r\n"
				+ "case where the first rotating machine is stationary, and the learning of the engagement\r\n"
				+ "position of the clutch can be executed during traveling during which the second rotating\r\n"
				+ "machine serves as a power source or while a vehicle remains stopped with the engine\r\n"
				+ "15 being in operation.\r\n"
				+ "[0012] It is preferable that the vehicle control device described above further\r\n"
				+ "includes an engine, the clutch connects and disconnects a flow of power between the\r\n"
				+ "engine, and the first rotating machine and a drive wheel, and the engagement position of\r\n"
				+ "the clutch is learned while a vehicle remains stopped with the engine being in operation.\r\n"
				+ "20 [0013] The vehicle control device according to the invention learns the\r\n"
				+ "engagement position of the clutch based on the change in the cogging torque during the\r\n"
				+ "change in the clutch stroke of the clutch in a case where the rotating machine is stationary.\r\n"
				+ "With the vehicle control device according to the invention, the engagement position can\r\n"
				+ "be learned without rotating the rotating machine and the generation of a loss attributable\r\n"
				+ "25 to the learning of the engagement position of the clutch can be inhibited.\r\n"
				+ "BRIEF DESCRIPTION OF THE DRAWINGS\r\n"
				+ "[0014] [FIG. 1] FIG. 1 is a skeleton diagram of a vehicle according to an\r\n"
				+ "4\r\n"
				+ "embodiment.\r\n"
				+ "[FIG. 2] FIG. 2 is a nomogram regarding an EV traveling mode of the\r\n"
				+ "embodiment.\r\n"
				+ "[FIG. 3] FIG. 3 is a diagram illustrating an example of cogging torque.\r\n"
				+ "[FIG. 4] FIG. 4 is a flowchart regarding learning control according 5 ng to the\r\n"
				+ "embodiment.\r\n"
				+ "[FIG. 5] FIG. 5 is a time chart regarding the learning control according to the\r\n"
				+ "embodiment.\r\n"
				+ "10 MODES FOR CARRYING OUT THE INVENTION\r\n"
				+ "[0015] Hereinafter, a vehicle control device according to an embodiment of the\r\n"
				+ "invention will be described in detail with reference to accompanying drawings. The\r\n"
				+ "invention is not limited to the embodiment. Components that constitute the following\r\n"
				+ "15 embodiment include those that can be easily assumed by those skilled in the art and those\r\n"
				+ "substantially identical thereto.\r\n"
				+ "[0016] [Embodiment]\r\n"
				+ "The embodiment will be described with reference to FIGS. 1 to 5. This\r\n"
				+ "embodiment relates to the vehicle control device. FIG. 1 is a skeleton diagram of a\r\n"
				+ "20 vehicle according to the embodiment of the invention. FIG. 2 is a nomogram regarding\r\n"
				+ "an EV traveling mode of the embodiment. FIG. 3 is a diagram illustrating an example of\r\n"
				+ "cogging torque. FIG. 4 is a flowchart regarding learning control according to the\r\n"
				+ "embodiment. FIG. 5 is a time chart regarding the learning control according to the\r\n"
				+ "embodiment.\r\n"
				+ "25 [0017] As illustrated in FIG. 1, a vehicle 100 is a hybrid vehicle that has an\r\n"
				+ "engine 1, a first rotating machine MG1, and a second rotating machine MG2. The\r\n"
				+ "vehicle 100 may be a plug-in hybrid vehicle (PHV) that can be charged by an external\r\n"
				+ "electric power supply. A vehicle control device 1-1 according to this embodiment is\r\n"
				+ "5\r\n"
				+ "configured to include the first rotating machine MG1, a clutch CL1, a rotation angle\r\n"
				+ "position detecting device 5, and an ECU 50. The vehicle control device 1-1 may be\r\n"
				+ "configured to include the engine 1, the second rotating machine MG2, a first planetary\r\n"
				+ "gear mechanism 10, and the like as well. A driving device for the vehicle 100 according\r\n"
				+ "to this embodiment can be applied to a front-engine, front-wheel-drive (FF) vehicle, 5 cle, a\r\n"
				+ "rear-engine, rear-wheel-drive (RR) vehicle, and the like. The driving device is mounted\r\n"
				+ "on the vehicle 100 for the axial direction of an input shaft 2 to correspond to, for example,\r\n"
				+ "the width direction of the vehicle.\r\n"
				+ "[0018] The engine 1, which is an example of engines, converts the combustion\r\n"
				+ "10 energy of a fuel into the rotary motion of an output shaft 1a and outputs the result. The\r\n"
				+ "output shaft 1a is connected to the input shaft 2 via the clutch CL1. The clutch CL1 is\r\n"
				+ "capable of transmitting torque to the first rotating machine MG1 when engaged. The\r\n"
				+ "clutch CL1 is a friction engagement-type clutch device such as a wet multi-plate-type\r\n"
				+ "clutch. The clutch CL1 according to this embodiment is configured to be capable of\r\n"
				+ "15 controlling a clutch stroke that is an engagement-direction stroke amount. The clutch\r\n"
				+ "CL1 is provided with, for example, a stroke sensor that detects the clutch stroke. The\r\n"
				+ "clutch CL1 according to this embodiment controls the clutch stroke when a supplied\r\n"
				+ "hydraulic pressure is regulated. The hydraulic pressure supplied to the clutch CL1 is\r\n"
				+ "feedback-controlled so that the detected clutch stroke corresponds to a target clutch\r\n"
				+ "20 stroke.\r\n"
				+ "[0019] The input shaft 2 is an input shaft of a power transmission unit and is\r\n"
				+ "arranged coaxially with the output shaft 1a and on an extension from the output shaft 1a.\r\n"
				+ "The input shaft 2 is connected to a first carrier 14 of the first planetary gear mechanism\r\n"
				+ "10 and rotates integrally with the first carrier 14.\r\n"
				+ "25 [0020] The first planetary gear mechanism 10 is an example of a differential\r\n"
				+ "mechanism in which the engine 1, the first rotating machine MG1, and the second\r\n"
				+ "rotating machine MG2 are connected to different rotating elements. The first planetary\r\n"
				+ "gear mechanism 10 is a single pinion-type planetary gear mechanism. The first\r\n"
				+ "6\r\n"
				+ "planetary gear mechanism 10 has a first sun gear 11, a first pinion gear 12, a first ring\r\n"
				+ "gear 13, and the first carrier 14.\r\n"
				+ "[0021] The first ring gear 13 is arranged coaxially with the first sun gear 11 and\r\n"
				+ "radially outside the first sun gear 11. The first pinion gear 12 is arranged between the\r\n"
				+ "first sun gear 11 and the first ring gear 13 and meshes with each of the first sun 5 un gear 11\r\n"
				+ "and the first ring gear 13. The first pinion gear 12 is rotatably supported by the first\r\n"
				+ "carrier 14. The first carrier 14 is connected to the input shaft 2 and rotates integrally\r\n"
				+ "with the input shaft 2. Accordingly, the first pinion gear 12 can rotate (revolve) about\r\n"
				+ "the central axis of the input shaft 2 with the input shaft 2 and can rotate (spin) about the\r\n"
				+ "10 central axis of the first pinion gear 12 by being supported by the first carrier 14.\r\n"
				+ "[0022] The first sun gear 11 is connected to a rotating shaft 33 of the first\r\n"
				+ "rotating machine MG1 and rotates integrally with a rotor 4 of the first rotating machine\r\n"
				+ "MG1. The first rotating machine MG1 is arranged on the engine 1 side with respect to\r\n"
				+ "the first planetary gear mechanism 10.\r\n"
				+ "15 [0023] A second planetary gear mechanism 20 is arranged coaxially with the\r\n"
				+ "first planetary gear mechanism 10 and on the side opposite to the engine 1 side. The\r\n"
				+ "second planetary gear mechanism 20 is arranged to be adjacent to the first planetary gear\r\n"
				+ "mechanism 10 and constitutes a complex planetary with the first planetary gear\r\n"
				+ "mechanism 10. The second planetary gear mechanism 20 functions as a deceleration\r\n"
				+ "20 planetary gear mechanism that decelerates the rotation of the second rotating machine\r\n"
				+ "MG2 and outputs the result. The second planetary gear mechanism 20 is a single\r\n"
				+ "pinion-type planetary gear mechanism. The second planetary gear mechanism 20 has a\r\n"
				+ "second sun gear 21, a second pinion gear 22, a second ring gear 23, and a second carrier\r\n"
				+ "24.\r\n"
				+ "25 [0024] The second ring gear 23 is arranged coaxially with the second sun gear\r\n"
				+ "21 and radially outside the second sun gear 21. The second pinion gear 22 is arranged\r\n"
				+ "between the second sun gear 21 and the second ring gear 23 and meshes with each of the\r\n"
				+ "second sun gear 21 and the second ring gear 23. The second pinion gear 22 is rotatably\r\n"
				+ "7\r\n"
				+ "supported by the second carrier 24. The second carrier 24 is fixed, not to be rotatable,\r\n"
				+ "on a vehicle body side. The second pinion gear 22 is supported by the second carrier 24\r\n"
				+ "and can rotate (spin) about the central axis of the second pinion gear 22.\r\n"
				+ "[0025] The second sun gear 21 is connected to a rotating shaft 34 of the second\r\n"
				+ "rotating machine MG2 and rotates integrally with a rotor 7 5 of the second rotating\r\n"
				+ "machine MG2. The second ring gear 23 is connected to the first ring gear 13 and rotates\r\n"
				+ "integrally with the first ring gear 13. A counter drive gear 25 is disposed on outer\r\n"
				+ "peripheral surfaces of the first ring gear 13 and the second ring gear 23. The counter\r\n"
				+ "drive gear 25 is an output gear that is disposed in output shafts of the first planetary gear\r\n"
				+ "10 mechanism 10 and the second planetary gear mechanism 20. The counter drive gear 25\r\n"
				+ "meshes with a counter driven gear 26. The counter driven gear 26 is connected to a\r\n"
				+ "drive pinion gear 28 via a counter shaft 27. The drive pinion gear 28 meshes with a\r\n"
				+ "differential ring gear 29 of a differential device 30. The differential device 30 is\r\n"
				+ "connected to drive wheels 32 via right and left driving shafts 31.\r\n"
				+ "15 [0026] Each of the first rotating machine MG1 and the second rotating machine\r\n"
				+ "MG2 functions as a motor (electric motor) and an electric power generator. The first\r\n"
				+ "rotating machine MG1 has a stator 3 that is fixed on the vehicle body side and the rotor 4\r\n"
				+ "that is rotatably supported. The second rotating machine MG2 has a stator 6 that is\r\n"
				+ "fixed on the vehicle body side and the rotor 7 that is rotatably supported. The first\r\n"
				+ "20 rotating machine MG1 and the second rotating machine MG2 are connected to a battery\r\n"
				+ "via inverters. The first rotating machine MG1 and the second rotating machine MG2\r\n"
				+ "can convert the electric power that is supplied from the battery into mechanical power\r\n"
				+ "and output the result and can convert mechanical power into electric power by being\r\n"
				+ "driven by input power. The electric power that is generated by the rotating machines\r\n"
				+ "25 MG1, MG2 can be stored in the battery. AC synchronous-type motor generators or the\r\n"
				+ "like can be used as the first rotating machine MG1 and the second rotating machine MG2.\r\n"
				+ "[0027] The rotation angle position detecting device 5 detects the rotation angle\r\n"
				+ "position of the rotor 4 of the first rotating machine MG1 (hereinafter, also referred to as\r\n"
				+ "8\r\n"
				+ "an “MG1 rotation angle position”). The rotation angle position detecting device 5\r\n"
				+ "according to this embodiment is a resolver and can accurately detect the MG1 rotation\r\n"
				+ "angle position. An oil pump OP is arranged in the end portion of the input shaft 2 on the\r\n"
				+ "side opposite to the engine 1 side. The oil pump OP is driven by the rotation of the\r\n"
				+ "input shaft 2 so that a lubricant is supplied to each portion 5 ion of the vehicle 100.\r\n"
				+ "[0028] The ECU 50 is an electronic control unit that has a computer. The ECU\r\n"
				+ "50 is electrically connected to the engine 1, the first rotating machine MG1, and the\r\n"
				+ "second rotating machine MG2. The ECU 50 can control each of the engine 1, the first\r\n"
				+ "rotating machine MG1, and the second rotating machine MG2. The ECU 50 can\r\n"
				+ "10 execute various types of control such as injection control, ignition control, and intake\r\n"
				+ "control regarding the engine 1. In addition, the ECU 50 can control the output torque of\r\n"
				+ "the first rotating machine MG1 (hereinafter, referred to as “MG1 torque”). In this\r\n"
				+ "embodiment, an input/output current with respect to the first rotating machine MG1\r\n"
				+ "(including an electric power generation amount) is regulated in accordance with a torque\r\n"
				+ "15 command value with respect to the first rotating machine MG1 so that the MG1 torque is\r\n"
				+ "controlled. In addition, the ECU 50 can control the output torque of the second rotating\r\n"
				+ "machine MG2 (hereinafter, referred to as “MG2 torque”). In this embodiment, an\r\n"
				+ "input/output current with respect to the second rotating machine MG2 (including an\r\n"
				+ "electric power generation amount) is regulated in accordance with a torque command\r\n"
				+ "20 value with respect to the second rotating machine MG2 so that the MG2 torque is\r\n"
				+ "controlled.\r\n"
				+ "[0029] The ECU 50 controls the clutch CL1. The ECU 50 outputs a clutch\r\n"
				+ "stroke command value to the clutch CL1. A hydraulic pressure control device (not\r\n"
				+ "illustrated) of the clutch CL1 regulates the engagement hydraulic pressure of the clutch\r\n"
				+ "25 CL1 with the clutch stroke command value set as the target clutch stroke. The ECU 50\r\n"
				+ "is electrically connected to the rotation angle position detecting device 5 and acquires the\r\n"
				+ "rotation angle position of the rotor 4 of the first rotating machine MG1 based on a\r\n"
				+ "detection result of the rotation angle position detecting device 5.\r\n"
				+ "9\r\n"
				+ "[0030] The vehicle 100 can selectively execute the EV traveling mode or a HV\r\n"
				+ "traveling mode. The EV traveling mode is a traveling mode in which traveling is\r\n"
				+ "performed with the second rotating machine MG2 serving as a power source. In the\r\n"
				+ "nomogram that is illustrated in FIG. 2, the S1 axis represents the first sun gear 11 and the\r\n"
				+ "rotation speed of the first rotating machine MG1 (hereinafter, 5 , referred to as an “MG1\r\n"
				+ "rotation speed”), the C1 axis represents the first carrier 14 and the rotation speed of the\r\n"
				+ "engine 1, and the R1 axis represents the rotation speed of the first ring gear 13. The\r\n"
				+ "quadrangular mark on the C1 axis represents an engine rotation speed Ne and the circular\r\n"
				+ "mark on the C1 axis represents a carrier rotation speed Nc that is the rotation speed of the\r\n"
				+ "10 first carrier 14.\r\n"
				+ "[0031] In FIG. 2, the S2 axis represents the rotation speed of the second rotating\r\n"
				+ "machine MG2 (hereinafter, referred to as an “MG2 rotation speed”), the C2 axis\r\n"
				+ "represents the rotation speed of the second carrier 24, and the R2 axis represents the\r\n"
				+ "rotation speed of the second ring gear 23. In this embodiment, the first ring gear 13 and\r\n"
				+ "15 the second ring gear 23 are connected to each other, and thus the rotation speeds of both\r\n"
				+ "correspond to each other.\r\n"
				+ "[0032] As illustrated in FIG. 2, the clutch CL1 is released during the EV\r\n"
				+ "traveling. During the EV traveling, the engine 1 is stationary and the carrier rotation\r\n"
				+ "speed Nc is the rotation speed in accordance with the speed of the vehicle. The second\r\n"
				+ "20 rotating machine MG2 can generate a forward driving force in the vehicle 100 based on\r\n"
				+ "the output of positive torque from the second ring gear 23 by outputting negative torque\r\n"
				+ "and causing negative rotation. Herein, positive rotation means the rotation of each of\r\n"
				+ "the ring gears 13, 23 during the forward traveling of the vehicle 100. The rotation of the\r\n"
				+ "second carrier 24 is restricted, and thus the second carrier 24 functions to receive a\r\n"
				+ "25 reaction force with respect to the MG2 torque and transmits the MG2 torque to the\r\n"
				+ "second ring gear 23.\r\n"
				+ "[0033] In this embodiment, the rotation of the first rotating machine MG1 is\r\n"
				+ "stopped during the EV traveling. The first rotating machine MG1 is maintained in a\r\n"
				+ "10\r\n"
				+ "state where the rotation is stopped by, for example, the cogging torque. The dragging\r\n"
				+ "loss or the like of the first rotating machine MG1 is reduced because the first rotating\r\n"
				+ "machine MG1 remains stationary.\r\n"
				+ "[0034] The HV traveling mode is a traveling mode in which traveling is\r\n"
				+ "performed with the engine 1 serving as a power source. In the HV traveling mode, 5 , the\r\n"
				+ "second rotating machine MG2 may also serve as a power source. In the HV traveling\r\n"
				+ "mode, the clutch CL1 is engaged. In the HV traveling mode, the first rotating machine\r\n"
				+ "MG1 functions to receive a reaction force with respect to engine torque. The first\r\n"
				+ "rotating machine MG1 functions to receive the reaction force with respect to the engine\r\n"
				+ "10 torque by outputting the MG1 torque and outputs the engine torque from the first ring\r\n"
				+ "gear 13. The first planetary gear mechanism 10 can function as a power dividing\r\n"
				+ "mechanism that distributes the engine torque to the first rotating machine MG1 side and\r\n"
				+ "an output side.\r\n"
				+ "[0035] It is preferable that an accurate engagement position of the clutch CL1 is\r\n"
				+ "15 grasped during the engagement and release control of the clutch CL1. The engagement\r\n"
				+ "position of the clutch CL1 is a clutch stroke at which the clutch CL1 begins to be\r\n"
				+ "engaged. The engagement position of the clutch CL1 is a clutch stroke at which\r\n"
				+ "engagement elements of the clutch CL1 are engaged with each other and torque begins to\r\n"
				+ "be transmitted when the clutch stroke of the clutch CL1 is gradually increased or a clutch\r\n"
				+ "20 stroke at which the engagement between the engagement elements is eliminated and the\r\n"
				+ "torque transmission is stopped when the clutch stroke is gradually decreased from a state\r\n"
				+ "where the engagement elements are engaged with each other.\r\n"
				+ "[0036] The vehicle control device 1-1 according to this embodiment performs\r\n"
				+ "the learning control regarding the engagement position of the clutch CL1. With regard\r\n"
				+ "25 to a case where the learning control regarding the engagement position of the clutch CL1\r\n"
				+ "is performed, it is considered that the engagement position is detected based on, for\r\n"
				+ "example, a fluctuation of the MG1 rotation speed available when the clutch CL1 is\r\n"
				+ "engaged or released during the rotation of the first rotating machine MG1. However,\r\n"
				+ "11\r\n"
				+ "this learning method based on the rotational position fluctuation is subjected to the\r\n"
				+ "generation of a loss attributable to the rotation of the first rotating machine MG1 or the\r\n"
				+ "like. In addition, the accuracy of the learning may lack uniformity in a case where the\r\n"
				+ "learning is based on a change in rotation.\r\n"
				+ "[0037] The vehicle control device 1-1 according to this embodiment 5 learns the\r\n"
				+ "engagement position of the clutch CL1 based on a change in the cogging torque during a\r\n"
				+ "change in the clutch stroke of the clutch CL1 in a case where the first rotating machine\r\n"
				+ "MG1 is stationary. Accordingly, the engagement position of the clutch CL1 can be\r\n"
				+ "learned without rotating the first rotating machine MG1, and thus the generation of the\r\n"
				+ "10 loss that is attributable to the learning of the engagement position of the clutch CL1 can\r\n"
				+ "be inhibited. In addition, the engagement position can be accurately learned whereas\r\n"
				+ "the engagement position learning method based on a change in the rotation of the first\r\n"
				+ "rotating machine MG1 lacks the accuracy.\r\n"
				+ "[0038] In the vehicle control device 1-1 according to this embodiment, the\r\n"
				+ "15 ECU 50 functions as a detection unit that detects the change in the cogging torque of the\r\n"
				+ "first rotating machine MG1. The ECU 50 detects the change in the cogging torque\r\n"
				+ "based on the detection result of the rotation angle position detecting device 5.\r\n"
				+ "Hereinafter, a method for detecting the change in the cogging torque will be described\r\n"
				+ "with reference to FIG. 3.\r\n"
				+ "20 [0039] As illustrated in FIG. 3, the cogging torque changes in, for example, a\r\n"
				+ "sinusoidal shape in accordance with the MG1 rotation angle position. The rotor 4 is\r\n"
				+ "stopped at a stable position (examples of which include a position at which the cogging\r\n"
				+ "torque is 0) at which, for example, a positive rotation-direction magnetic force and a\r\n"
				+ "negative rotation-direction magnetic force are balanced with each other in a state where\r\n"
				+ "25 the input/output current of the first rotating machine MG1 is absent. In a case where\r\n"
				+ "torque is input to the rotor 4 from the outside and the input torque from the outside is\r\n"
				+ "torque between a positive extreme value Tc1 and a negative extreme value Tc2 of the\r\n"
				+ "cogging torque, the input torque and the cogging torque are balanced with each other and\r\n"
				+ "12\r\n"
				+ "the rotor 4 is stopped at the torque-balanced MG1 rotation angle position.\r\n"
				+ "[0040] Accordingly, the change in the cogging torque can be detected based on a\r\n"
				+ "change in the MG1 rotation angle position when the first rotating machine MG1 is\r\n"
				+ "stationary. In a case where the learning control regarding the engagement position of\r\n"
				+ "the clutch CL1 is performed, the ECU 50 allows the clutch CL1 to be engaged from 5 a\r\n"
				+ "state where the first rotating machine MG1 is stationary. When the engagement of the\r\n"
				+ "clutch CL1 is initiated, torque begins to be transmitted to the rotor 4 of the first rotating\r\n"
				+ "machine MG1 or the torque transmitted to the rotor 4 changes. In a case where the input\r\n"
				+ "torque with respect to the rotor 4 changes to the negative torque side, for example, the\r\n"
				+ "10 MG1 rotation angle position changes to a cogging torque-increasing side as illustrated by\r\n"
				+ "an arrow Y1. In a case where the input torque with respect to the rotor 4 changes to the\r\n"
				+ "positive torque side, the MG1 rotation angle position changes to a cogging\r\n"
				+ "torque-decreasing side as illustrated by an arrow Y2. In other words, the change in the\r\n"
				+ "MG1 rotation angle position shows a change in the cogging torque of the first rotating\r\n"
				+ "15 machine MG1 and shows a change in the input torque with respect to the rotor 4. The\r\n"
				+ "ECU 50 detects the engagement position of the clutch based on the change in the cogging\r\n"
				+ "torque attributable to this change in the input torque with respect to the rotor 4.\r\n"
				+ "[0041] Specifically, the ECU 50 can learn, as the engagement position of the\r\n"
				+ "clutch CL1, the clutch stroke at which the MG1 rotation angle position begins to change\r\n"
				+ "20 when the clutch stroke is gradually increased from a state where the clutch CL1 is\r\n"
				+ "released. In addition, the ECU 50 does not learn, as the engagement position, the clutch\r\n"
				+ "stroke at which the MG1 rotation angle position does not change when the clutch stroke\r\n"
				+ "is gradually increased.\r\n"
				+ "[0042] In addition, the ECU 50 can learn, as the engagement position of the\r\n"
				+ "25 clutch CL1, the clutch stroke at which the MG1 rotation angle position begins to remain\r\n"
				+ "unchanged when the clutch stroke is gradually decreased from a state where the clutch\r\n"
				+ "CL1 is engaged and the rotation of the first rotating machine MG1 is stopped by the\r\n"
				+ "cogging torque. In addition, the ECU 50 does not learn, as the engagement position, the\r\n"
				+ "13\r\n"
				+ "clutch stroke at which the MG1 rotation angle position changes when the clutch stroke is\r\n"
				+ "gradually decreased.\r\n"
				+ "[0043] Since the learning method regarding the engagement position of the\r\n"
				+ "clutch CL1 according to this embodiment is based on a change in the value that is\r\n"
				+ "detected by the rotation angle position detecting device 5, the engagement position 5 on can be\r\n"
				+ "accurately detected. Hereinafter, engagement position learning control according to this\r\n"
				+ "embodiment will be described with reference to FIGS. 4 and 5. The control flow that is\r\n"
				+ "illustrated in FIG. 4 is repeatedly executed at predetermined time intervals when, for\r\n"
				+ "example, the engagement position of the clutch CL1 needs to be learned.\r\n"
				+ "10 [0044] In Step S101, the ECU 50 determines whether or not traveling is in\r\n"
				+ "progress in a separated state. The ECU 50 performs a positive determination in Step\r\n"
				+ "S101 when, for example, the traveling is in progress with the clutch CL1 released. In\r\n"
				+ "Step S101, it is determined whether or not the learning control regarding the engagement\r\n"
				+ "position of the clutch CL1 can be initiated. In a case where the engagement position\r\n"
				+ "15 learning control is executed, the first rotating machine MG1 may be shut down and may\r\n"
				+ "be stopped by the cogging torque. The ECU 50 performs the positive determination in\r\n"
				+ "Step S101 during, for example, the EV traveling and learns the engagement position of\r\n"
				+ "the clutch CL1. The processing proceeds to Step S102 in a case where it is determined\r\n"
				+ "as a result of the determination of Step S101 that the traveling in the separated state is in\r\n"
				+ "20 progress (Step S101-Y). Otherwise (Step S101-N), this control flow is terminated.\r\n"
				+ "[0045] In Step S102, the ECU 50 strokes the clutch CL1 up to a learning\r\n"
				+ "initiation point. The learning initiation point that is illustrated in FIG. 5 is appropriately\r\n"
				+ "set to a stroke ahead of an engagement initiation position. When an increase in the\r\n"
				+ "clutch stroke is initiated from the learning initiation point, a learning period can be\r\n"
				+ "25 shortened than in a case where the increase in the clutch stroke is initiated from 0. The\r\n"
				+ "ECU 50 outputs a clutch stroke st1 at the learning initiation point as the clutch stroke\r\n"
				+ "command value with respect to the clutch CL1. The processing proceeds to Step S103\r\n"
				+ "after the execution of Step S102.\r\n"
				+ "14\r\n"
				+ "[0046] In Step S103, the ECU 50 moves the clutch stroke by a stroke change\r\n"
				+ "amount &#61508;strk from the current stroke. The stroke change amount &#61508;strk is a positive\r\n"
				+ "clutch stroke. In this embodiment, the stroke change amount &#61508;strk is the minimum\r\n"
				+ "movement amount of the clutch stroke. The ECU 50 increases the clutch stroke\r\n"
				+ "command value by the stroke change amount &#61508;strk and moves the engagement 5 nt element\r\n"
				+ "of the clutch CL1 in the engagement direction. The processing proceeds to Step S104\r\n"
				+ "after the execution of Step S103.\r\n"
				+ "[0047] In Step S104, the ECU 50 determines whether or not an MG1 resolver\r\n"
				+ "angle is changed. The ECU 50 determines whether or not the MG1 rotation angle\r\n"
				+ "10 position detected by the rotation angle position detecting device 5 is changed before and\r\n"
				+ "after the clutch stroke command value is changed in Step S103. The processing\r\n"
				+ "proceeds to Step S105 in a case where it is determined as a result of the determination of\r\n"
				+ "Step S104 that the MG1 resolver angle is changed (Step S104-Y). Otherwise (Step\r\n"
				+ "S104-N), the processing proceeds to Step S103 and the clutch stroke is increased.\r\n"
				+ "15 [0048] In Step S105, the ECU 50 sets the current stroke to a learning point 1.\r\n"
				+ "In FIG. 5, the MG1 resolver angle begins to change at time t1 and a current stroke st4\r\n"
				+ "available in this case is set to the learning point 1. The processing proceeds to Step\r\n"
				+ "S106 after the execution of Step S105.\r\n"
				+ "[0049] In Step S106, the ECU 50 moves the clutch stroke by the stroke change\r\n"
				+ "20 amount &#61508;strk from the current stroke. The ECU 50 increases the clutch stroke\r\n"
				+ "command value by the stroke change amount &#61508;strk and moves the engagement element\r\n"
				+ "of the clutch CL1 further in the engagement direction. The processing proceeds to Step\r\n"
				+ "S107 after the execution of Step S106.\r\n"
				+ "[0050] In Step S107, the ECU 50 determines whether or not the clutch stroke\r\n"
				+ "25 reaches a predetermined stroke. The predetermined stroke, which is determined in\r\n"
				+ "advance, is a clutch stroke exceeding the clutch stroke at the engagement position. As\r\n"
				+ "illustrated in FIG. 5, a predetermined stroke st5 is a value that exceeds the learning point\r\n"
				+ "1 (clutch stroke st4). In this embodiment, the learning of the engagement position that\r\n"
				+ "15\r\n"
				+ "is performed while the clutch CL1 is engaged is terminated when the clutch stroke\r\n"
				+ "reaches the predetermined stroke st5. When the clutch stroke reaches the predetermined\r\n"
				+ "stroke st5, the ECU 50 moves the engagement element of the clutch CL1 in a release\r\n"
				+ "direction and performs the learning of the engagement position. The processing\r\n"
				+ "proceeds to Step S108 in a case where it is determined as a result of the determination 5 n of\r\n"
				+ "Step S107 that the clutch stroke reaches the predetermined stroke (Step S107-Y).\r\n"
				+ "Otherwise (Step S107-N), the processing proceeds to Step S106 and the clutch stroke is\r\n"
				+ "increased.\r\n"
				+ "[0051] In Step S108, the ECU 50 moves the clutch stroke by the stroke change\r\n"
				+ "10 amount &#61508;strk in the release direction from the current stroke. The ECU 50 moves the\r\n"
				+ "engagement element of the clutch CL1 in the release direction by decreasing the clutch\r\n"
				+ "stroke command value by the stroke change amount &#61508;strk. The processing proceeds to\r\n"
				+ "Step S109 after the execution of Step S108.\r\n"
				+ "[0052] In Step S109, the ECU 50 determines whether or not the MG1 resolver\r\n"
				+ "15 angle remains unchanged. The ECU 50 determines whether or not the MG1 rotation\r\n"
				+ "angle position detected by the rotation angle position detecting device 5 remains\r\n"
				+ "unchanged before and after the clutch stroke command value is changed in Step S108.\r\n"
				+ "The processing proceeds to Step S110 in a case where it is determined as a result of the\r\n"
				+ "determination of Step S109 that the MG1 resolver angle remains unchanged (Step\r\n"
				+ "20 S109-Y). Otherwise (Step S109-N), the processing proceeds to Step S108 and the\r\n"
				+ "clutch stroke is decreased.\r\n"
				+ "[0053] In Step S110, the ECU 50 sets the current stroke to a learning point 2.\r\n"
				+ "In FIG. 5, no change in the MG1 resolver angle is detected from time t2 and a current\r\n"
				+ "stroke st2 available in this case is set to the learning point 2. The processing proceeds to\r\n"
				+ "25 Step S111 after the execution of Step S110.\r\n"
				+ "[0054] In Step S111, the ECU 50 learns the clutch stroke that is calculated by\r\n"
				+ "the following formula (1) as the engagement initiation position.\r\n"
				+ "{(learning point 1-&#61508;strk)+(learning point 2+&#61508;strk)}/2…(1)\r\n"
				+ "16\r\n"
				+ "(learning point 1-&#61508;strk) in this formula (1), which is the clutch stroke at which the\r\n"
				+ "MG1 rotation angle position begins to change, is a clutch stroke st3 in the case of FIG. 5.\r\n"
				+ "(learning point 2+&#61508;strk) in this formula (1), which is the clutch stroke at which the MG1\r\n"
				+ "rotation angle position begins to remain unchanged, is the clutch stroke st3 in the case of\r\n"
				+ "FIG. 5 5.\r\n"
				+ "[0055] In other words, the ECU 50 learns, as the engagement position of the\r\n"
				+ "clutch CL1, the average stroke of the clutch stroke (learning point 1-&#61508;strk) at which the\r\n"
				+ "MG1 rotation angle position begins to change during an increase in clutch stroke and the\r\n"
				+ "clutch stroke (learning point 2+&#61508;strk) at which the MG1 rotation angle position begins to\r\n"
				+ "10 remain unchanged during a decrease in clutch stroke. A learning variation can be\r\n"
				+ "reduced since the average stroke is the engagement position. This control flow is\r\n"
				+ "terminated after the execution of Step S111.\r\n"
				+ "[0056] With the vehicle control device 1-1 according to this embodiment, the\r\n"
				+ "engagement position of the clutch CL1 can be learned without rotating the first rotating\r\n"
				+ "15 machine MG1. Accordingly, the generation of a loss attributable to, for example,\r\n"
				+ "co-rotation of the first rotating machine MG1 can be inhibited. In addition, the\r\n"
				+ "engagement position of the clutch CL1 can be accurately learned.\r\n"
				+ "[0057] The ECU 50 may learn the clutch stroke (learning point 1-&#61508;strk) at\r\n"
				+ "which the MG1 rotation angle position begins to change as the engagement position\r\n"
				+ "20 instead of learning the average stroke as the engagement position. In addition, the ECU\r\n"
				+ "50 may learn the clutch stroke (learning point 2+&#61508;strk) at which the MG1 rotation angle\r\n"
				+ "position begins to remain unchanged as the engagement position.\r\n"
				+ "[0058] [First Modification Example of Embodiment]\r\n"
				+ "The clutch stroke at which the MG1 rotation angle position begins to change may\r\n"
				+ "25 be the learning point 1 or another clutch stroke. In other words, the clutch stroke at\r\n"
				+ "which the MG1 rotation angle position begins to change may be the clutch stroke\r\n"
				+ "immediately before the change in the MG1 rotation angle position or the clutch stroke\r\n"
				+ "immediately after the change in the MG1 rotation angle position available when the\r\n"
				+ "17\r\n"
				+ "clutch stroke command value is gradually increased by stroke change amount &#61508;strk.\r\n"
				+ "[0059] The clutch stroke at which the MG1 rotation angle position begins to\r\n"
				+ "remain unchanged may be the learning point 2 or may be another clutch stroke. In other\r\n"
				+ "words, the clutch stroke at which the MG1 rotation angle position begins to remain\r\n"
				+ "unchanged may be the clutch stroke available immediately before the MG1 rotation 5 on angle\r\n"
				+ "position begins to remain unchanged or the clutch stroke available immediately after the\r\n"
				+ "MG1 rotation angle position begins to remain unchanged when the clutch stroke\r\n"
				+ "command value is gradually decreased by stroke change amount &#61508;strk.\r\n"
				+ "[0060] [Second Modification Example of Embodiment]\r\n"
				+ "10 In the embodiment described above, the learning control regarding the engagement\r\n"
				+ "position of the clutch CL1 is executed during the traveling of the vehicle 100. However,\r\n"
				+ "the learning control can also be executed in another situation in which the clutch CL1 is\r\n"
				+ "subjected to a differential rotation. For example, the engagement position of the clutch\r\n"
				+ "CL1 can be learned in a situation in which the vehicle 100 is stopped and the engine 1 is\r\n"
				+ "15 in operation. In this case, the ECU 50 can learn the engagement position when the\r\n"
				+ "clutch stroke is gradually increased from a state where the vehicle 100 remains stopped,\r\n"
				+ "the engine 1 is in operation, the first rotating machine MG1 is stopped, and the clutch\r\n"
				+ "CL1 is released. As in the embodiment described above, the clutch stroke at which the\r\n"
				+ "MG1 rotation angle position begins to change may be learned as the engagement position\r\n"
				+ "20 of the clutch CL1.\r\n"
				+ "[0061] In addition, the ECU 50 can learn the engagement position when the\r\n"
				+ "clutch stroke is gradually decreased from a state where the vehicle 100 remains stopped,\r\n"
				+ "the engine 1 is in operation, the first rotating machine MG1 is stopped, and the clutch\r\n"
				+ "CL1 is engaged. As in the embodiment described above, the clutch stroke at which the\r\n"
				+ "25 MG1 rotation angle position begins to remain unchanged may be learned as the\r\n"
				+ "engagement position of the clutch CL1.\r\n"
				+ "[0062] [Third Modification Example of Embodiment]\r\n"
				+ "In the embodiment described above, the ECU 50 detects the engagement position\r\n"
				+ "18\r\n"
				+ "while gradually engaging the clutch CL1 before detecting the engagement position while\r\n"
				+ "gradually releasing the clutch CL1. However, the learning of the engagement position\r\n"
				+ "may also be performed in reverse order.\r\n"
				+ "[0063] [Fourth Modification Example of Embodiment]\r\n"
				+ "In the embodiment described above, the stroke change amount &#61508;strk 5 is the\r\n"
				+ "minimum movement amount of the clutch CL1. However, the stroke change amount\r\n"
				+ "&#61508;strk is not limited thereto. The stroke change amount &#61508;strk may be a clutch stroke that\r\n"
				+ "exceeds the minimum movement amount or the stroke change amount &#61508;strk may\r\n"
				+ "correspond to several steps of the minimum movement amount. The stroke change\r\n"
				+ "10 amount &#61508;strk may be determined for the magnitude of the input torque of the first\r\n"
				+ "rotating machine MG1 not to become equal to or greater than maximum cogging torque\r\n"
				+ "(magnitude of the positive extreme value Tc1 and the negative extreme value Tc2) due to\r\n"
				+ "a change in clutch torque capacity during the change in clutch stroke by the stroke change\r\n"
				+ "amount &#61508;strk.\r\n"
				+ "15 [0064] [Fifth Modification Example of Embodiment]\r\n"
				+ "The vehicle 100, to which the invention is applied, is not limited to the example of\r\n"
				+ "the embodiment. For example, the vehicle control device 1-1 according to the\r\n"
				+ "embodiment can also be applied to a vehicle on which an engine, a rotating machine, and\r\n"
				+ "a clutch that connects and disconnects the rotating machine and a drive wheel from the\r\n"
				+ "20 engine are mounted. In this vehicle, the learning control regarding the engagement\r\n"
				+ "position of the clutch can be performed in a state where the vehicle remains stopped, the\r\n"
				+ "clutch is released, the rotating machine is stopped, and the engine is in operation. In\r\n"
				+ "addition, the learning control regarding the engagement position of the clutch can be\r\n"
				+ "performed in a state where the vehicle remains stopped, the engine is in operation, and\r\n"
				+ "25 the clutch is engaged so that the rotating machine is stopped by the cogging torque. For\r\n"
				+ "example, the engagement position of the clutch can be learned as in the second\r\n"
				+ "modification example.\r\n"
				+ "[0065] [Sixth Modification Example of Embodiment]\r\n"
				+ "19\r\n"
				+ "In the embodiment described above, the change in the cogging torque is detected\r\n"
				+ "based on the detection result of the rotation angle position detecting device 5. However,\r\n"
				+ "the change in the cogging torque may also be detected by another method. In addition,\r\n"
				+ "the rotation angle position detecting device 5 is not limited to the resolver. The rotation\r\n"
				+ "angle position detecting device 5 is not particularly limited insofar as a change 5 in the\r\n"
				+ "MG1 rotation angle position attributable to the change in the cogging torque can be\r\n"
				+ "detected therewith.\r\n"
				+ "[0066] [Seventh Modification Example of Embodiment]\r\n"
				+ "In the embodiment described above, the first rotating machine MG1 is connected to\r\n"
				+ "10 the first sun gear 11 and the clutch CL1 is connected to the first carrier 14. However,\r\n"
				+ "the invention is not limited thereto. For example, each of the first rotating machine\r\n"
				+ "MG1 and the clutch CL1 may be connected to a rotating element of the first planetary\r\n"
				+ "gear mechanism 10 other than these rotating elements according to the embodiment\r\n"
				+ "described above. In addition, the first rotating machine MG1 and the clutch CL1 may\r\n"
				+ "15 be connected without the differential mechanism such as the first planetary gear\r\n"
				+ "mechanism 10. In other words, the clutch CL1 may be arranged in any form insofar as\r\n"
				+ "the clutch CL1 can transmit the torque to the first rotating machine MG1 when engaged.\r\n"
				+ "[0067] In addition, the engine 1, the first rotating machine MG1, and the second\r\n"
				+ "rotating machine MG2 may be connected to rotating elements of the first planetary gear\r\n"
				+ "20 mechanism 10 other than the rotating elements according to the embodiment described\r\n"
				+ "above.\r\n"
				+ "[0068] The details that are disclosed in the embodiment and the modification\r\n"
				+ "examples described above can be appropriately combined with each other in execution.\r\n"
				+ "25 REFERENCE SIGNS LIST\r\n"
				+ "[0069] 1-1 … VEHICLE CONTROL DEVICE, 1 … ENGINE, 3 … STATOR, 4\r\n"
				+ "… ROTOR, 5 … ROTATION ANGLE POSITION DETECTING DEVICE, 32 …\r\n"
				+ "20\r\n"
				+ "DRIVE WHEEL, 33, 34 … ROTATING SHAFT, 50 … ECU, CL1 … CLUTCH, MG1\r\n"
				+ "… FIRST ROTATING MACHINE, MG2 … SECOND ROTATING MACHINE, &#61508;STRK\r\n"
				+ "");
		tm.getInventor().add(inventor);

		SessionFactory sf = new Configuration().configure().buildSessionFactory();
		System.out.println("session created");
		Session session = sf.openSession();

		session.beginTransaction();
		session.save(tm);
		session.getTransaction().commit();
		session.close();
		System.out.println("session ended");
	}
}

//Connection connection = null;
//Statement statement = null;
//
//try {
//    // Register JDBC driver
//    Class.forName("oracle.jdbc.driver.OracleDriver");
//
//    // Open a connection
//    connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
//    System.out.println("Connected to Oracle database");
//
//    // Create a statement
//    statement = connection.createStatement();
//
//    // Insert data into the table
//    //String insertDataSQL = "INSERT INTO EXAMPLE_TABLE (ID, NAME, AGE) VALUES (3, 'naman', 25)";
//    //statement.executeUpdate(insertDataSQL);
//    ResultSet rs = statement.executeQuery("SELECT * FROM EXAMPLE_TABLE");
//    while(rs.next()!= false) {
//    	System.out.println(rs.getString("NAME"));
//    }
//    System.out.println("Data inserted successfully");
//
//} catch (ClassNotFoundException | SQLException e) {
//    e.printStackTrace();
//} finally {
//    // Close resources
//    try {
//        if (statement != null) statement.close();
//        if (connection != null) connection.close();
//    } catch (SQLException e) {
//        e.printStackTrace();
//    }
//}